version: '3.8'

services:
 app:
   ports:
     - "8000:80"
   build: ./docker/app
   container_name: laravel-app
   volumes:
     - ./src:/var/www/html

 # MySQL
 db:
   image: mysql:5.7
   container_name: mysql
   ports:
     - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: default
     MYSQL_USER: root
     MYSQL_PASSWORD: secret
     TZ: 'Asia/Tokyo'
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

 # phpmyadmin
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
     - 8080:80
   environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mysql
     - PMA_USER=root
     - PMA_PASSWORD=root
   container_name: "phpmyadmin"