version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: deploy
          - DB_CONNECTION: mysql
          - DB_DATABASE: deployment_01
          - DB_USERNAME: root
 
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: deployment_01
 
    steps:
      - checkout
 
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
 
      - restore_cache:
          key: - composer-v2-{{ checksum "src/laravelapp/composer.lock" }}
      
      - restore_cache:
          key: npm-v2-{{ checksum "src/laravelapp/package-lock.json" }}

      - run: composer install -n --prefer-dist
 
      - save_cache:
          key: npm-v2-{{ checksum "src/laravelapp/package-lock.json" }}
          paths:
            - src/laravelapp/node_modules
 
      - run: 
          working_directory: src/laravelapp
          echo "APP_KEY=" > .env.deplpy
      - run: 
          working_directory: src/laravelapp
          php artisan key:generate
      - run:
          working_directory: src/laravelapp
          php artisan migrate
 
      - run: src/laravelapp/vendor/bin/phpunit