version: 2.1
jobs:
  build:
    docker:

      - image: circleci/php:7.4-node-browsers

      - restore_cache:
          key: composer-v2-{{ checksum "src/laravelapp/composer.lock" }}

      - restore_cache:
          key: npm-v2-{{ checksum "src/laravelapp/package-lock.json" }}

      - save_cache:
          key: npm-v2-{{ checksum "src/laravelapp/package-lock.json" }}
          paths:
            - src/laravelapp/node_modules
      - run:
          working_directory: src/laravelapp
          command: npm run dev
      - run:
          working_directory: src/laravelapp
          name: php test
          command: vendor/bin/phpunit

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run: sudo docker-php-ext-install pdo_mysql

      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          working_directory: src/laravelapp
          command: composer install -n --prefer-dist

      - save_cache:
          key: composer-v2-{{ checksum "src/laravelapp/composer.lock" }}
          paths:
            - src/laravelapp/vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run:
          working_directory: src/laravelapp
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      # prepare the database
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run
