# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    # Specify the version you desire here
    - image: circleci/php:7.4-node-browsers
      
    environment:
      - APP_DEBUG: true
      - APP_ENV: deploy
      - APP_KEY: base64:RH/f4NgS/ypZQ2q20YVcfdyB20/Be9gaRHAVEw+nS2A=
      - DB_CONNECTION: mysql
      - DB_DATABASE: default
      - DB_USERNAME: root

    steps:
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip

      - run:
          name: "Create Environment file"
          command: |
            mv laravel/.env.deploy .env

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "laravel/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          working_directory: laravel
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "laravel/composer.json" }}
          paths:
            - laravel/vendor